# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug Report
description: File a bug report
name: "Bug report"
body:
- type: markdown
  attributes:
    value: "Thanks for taking the time to fill out this bug report!"
- type: textarea
  attributes:
    label: "What's wrong?"
    
  # Add more fields as needed
